name: mmg_toolbox
channels:
  - conda-forge
dependencies:
  - python=3.13
  - numpy
  - matplotlib-base
  - jupyter
  - nbconvert
  - papermill
  - h5py
  - hdf5plugin
  - imageio
  - scipy
  - lmfit
  - hdfmap
  - pip
  - pip:
      - nexus2srs
      - mmg_toolbox
      - dominate
