name: mmg_toolbox
channels:
  - conda-forge
dependencies:
  - python=3.13
  - numpy
  - matplotlib-base
  - jupyter
  - nbconvert
  - papermill
  - pyvista
  - marimo
  - pandas
  - plotly
  - h5py
  - hdf5plugin
  - imageio
  - scipy
  - dominate
  - lmfit
  - hdfmap
  - pip
  - pip:
      - nexus2srs
      - mmg_toolbox
